// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btusehwcjqylfbemwkya.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0dXNlaHdjanF5bGZiZW13a3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMjY4MDAsImV4cCI6MjA4NTYwMjgwMH0.YAH7vDl34gKQkCdVyG-pgDSi05RVzE5tNI9RW2rGQiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
