// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzrdtxrplzcvfotzndrp.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cmR0eHJwbHpjdmZvdHpuZHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0MjUxMTksImV4cCI6MjA4MzAwMTExOX0.NteV632AbIgVO4hv5vH0vWic04dDdhLndognu-8ruPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});